name = "Hugo Atom Feed"
license = "GPLv3"
licenselink = "https://github.com/rowanmanning/hugo-atom-feed/blob/master/LICENSE"
description = "Hugo theme component for creating ATOM feeds for Hugo 'list' pages"
homepage = "https://github.com/rowanmanning/hugo-atom-feed"
tags = ["component", "feed", "atom", "output-format"]
features = ["atom"]
min_version = "0.58"

[author]
  name = "Rowan Manning"
  homepage = "https://rowanmanning.com"
